
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nimesha
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    Connection conn;
ResultSet rs;
PreparedStatement pst;
PreparedStatement ps;
    public AdminPage() {
        
        conn=javaConnect.connecrDb();
        initComponents();
        Random();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        view = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        freePanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        AddPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        dob = new org.jdesktop.swingx.JXDatePicker();
        add_librarian = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        ViewPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        view_id = new javax.swing.JTextField();
        view_view = new javax.swing.JButton();
        ViewPanel2 = new javax.swing.JPanel();
        view_address = new javax.swing.JTextField();
        view_email = new javax.swing.JTextField();
        view_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        view_edit = new javax.swing.JButton();
        view_nic = new javax.swing.JTextField();
        view_phone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        view_dob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DeletePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Delete_table = new javax.swing.JTable();
        delete_librarian = new javax.swing.JButton();
        back = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/signup.png"))); // NOI18N
        add.setText("Add ");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 50));

        view.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/search user icon.png"))); // NOI18N
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel2.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 132, 50));

        logout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/0-2967_png-file-svg-logout-logo-png.png.jpg"))); // NOI18N
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 148, 50));

        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/adminmenu.jpg"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 960, 80));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        freePanel.setBackground(new java.awt.Color(204, 204, 255));
        freePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/How-to-format-a-book.jpg"))); // NOI18N
        freePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1010, 530));

        jPanel3.add(freePanel, "card5");

        AddPanel.setBackground(new java.awt.Color(153, 153, 255));
        AddPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DOB");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Email Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Address");

        add_librarian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_librarian.setText("Add Librarian");
        add_librarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_librarianActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("NIC Number");

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_librarian)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(102, 102, 102))
                            .addGroup(AddPanelLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(110, 110, 110)))
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_librarian)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel3.add(AddPanel, "card2");

        ViewPanel1.setBackground(new java.awt.Color(153, 153, 255));
        ViewPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Enetr the ID:");

        view_view.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/search user icon.png"))); // NOI18N
        view_view.setText("view librarian");
        view_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_viewActionPerformed(evt);
            }
        });

        ViewPanel2.setBackground(new java.awt.Color(102, 102, 255));
        ViewPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Librarian Details:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("DOB");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Address");

        view_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/edit icon.png"))); // NOI18N
        view_edit.setText("Edit Librarian");
        view_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_editActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("NIC");

        view_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_dobActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Full Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Email Address");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Phone");

        javax.swing.GroupLayout ViewPanel2Layout = new javax.swing.GroupLayout(ViewPanel2);
        ViewPanel2.setLayout(ViewPanel2Layout);
        ViewPanel2Layout.setHorizontalGroup(
            ViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewPanel2Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(view_edit))
                    .addGroup(ViewPanel2Layout.createSequentialGroup()
                        .addGroup(ViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addGroup(ViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(view_address, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(view_email)
                            .addComponent(view_name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(view_dob)
                            .addComponent(view_nic)
                            .addComponent(view_phone))))
                .addContainerGap())
        );
        ViewPanel2Layout.setVerticalGroup(
            ViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ViewPanel2Layout.createSequentialGroup()
                        .addComponent(view_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(view_edit))
                    .addGroup(ViewPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(44, 44, 44)))
                .addContainerGap())
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/addcustomer.png"))); // NOI18N

        javax.swing.GroupLayout ViewPanel1Layout = new javax.swing.GroupLayout(ViewPanel1);
        ViewPanel1.setLayout(ViewPanel1Layout);
        ViewPanel1Layout.setHorizontalGroup(
            ViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(73, 73, 73)
                .addComponent(view_id, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(view_view)
                .addGap(94, 94, 94))
            .addGroup(ViewPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(ViewPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        ViewPanel1Layout.setVerticalGroup(
            ViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_view)
                    .addComponent(jLabel8))
                .addGroup(ViewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ViewPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel3.add(ViewPanel1, "card2");

        DeletePanel.setBackground(new java.awt.Color(153, 153, 255));
        DeletePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)), "Librarian details:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        Delete_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Delete_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "NIC", "Phone", "email", "DOB", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Delete_table);

        delete_librarian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_librarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/delete.png"))); // NOI18N
        delete_librarian.setText("Delete Librarian");
        delete_librarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_librarianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeletePanelLayout = new javax.swing.GroupLayout(DeletePanel);
        DeletePanel.setLayout(DeletePanelLayout);
        DeletePanelLayout.setHorizontalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeletePanelLayout.createSequentialGroup()
                .addContainerGap(741, Short.MAX_VALUE)
                .addComponent(delete_librarian)
                .addGap(36, 36, 36))
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addContainerGap())
        );
        DeletePanelLayout.setVerticalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(delete_librarian)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel3.add(DeletePanel, "card2");

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/back.jpg"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/Actions-window-close-icon.png"))); // NOI18N
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1115, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addComponent(close))
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void Random(){
        Random rd=new Random();
        id.setText(""+rd.nextInt(1000+1));
        
    }
    private void view_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_dobActionPerformed
private void display(){
    try{
        String lib="select * from librarian";
 PreparedStatement pst=conn.prepareStatement(lib);
        rs=pst.executeQuery();
        DefaultTableModel tm=(DefaultTableModel)Delete_table.getModel();
         tm.setRowCount(0);
         while(rs.next()){
             Object o[]={rs.getInt("id"),rs.getString("fullname"),rs.getString("nic"),rs.getInt("phone"),rs.getString("email"),rs.getString("dob"),rs.getString("address")};
              tm.addRow(o);
             }
        }catch(Exception ex){
        System.out.println(ex);
    }
     
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(AddPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_addActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(ViewPanel1);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_viewActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(DeletePanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        display();
    }//GEN-LAST:event_deleteActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed
private boolean isValid(String email){
     String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      return email.matches(regex);
   
}
    private void add_librarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_librarianActionPerformed
        // TODO add your handling code here:
        if(!"".equals(name.getText())&&!"".equals(dob.getEditor().getText())&&!"".equals(nic.getText())&&!"".equals(phone.getText())&&!"".equals(email.getText())&&!"".equals(address.getText())){
          if(isValid(email.getText())){
          if(phone.getText().length()==10){
          String sql="insert into librarian(id,fullname,DOB,NIC,phone,email,address) values(?,?,?,?,?,?,?)";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, id.getText());
            pst.setString(2, name.getText());
            pst.setString(3, dob.getEditor().getText());
            pst.setString(4, nic.getText());
            pst.setString(5, phone.getText());
            pst.setString(6, email.getText());
            pst.setString(7, address.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "new librarian added");
            id.setText("");
            name.setText("");
            dob.getEditor().setText("");
            nic.setText("");
            phone.setText("");
            email.setText("");
            address.setText("");
        }catch(Exception e){
            System.out.println(e);
        }    
          } else{
               JOptionPane.showMessageDialog(null,"insert a correct phone number");
          }
        
        
        }else{
            JOptionPane.showMessageDialog(null,"insert a correct email address");
        }   
        }else{
            JOptionPane.showMessageDialog(null,"please fill all the text fields"); 
        }
       
    }//GEN-LAST:event_add_librarianActionPerformed

    private void view_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_viewActionPerformed
        // TODO add your handling code here:
        try{
        String lib="Select * from librarian where id=?"  ;
       pst=conn.prepareStatement(lib);
       pst.setString(1,view_id.getText());
        rs=pst.executeQuery();
        if(rs.next()){
           
                 view_name.setText(rs.getString("fullname"));
                 view_dob.setText(rs.getString("dob"));
                 view_nic.setText(rs.getString("nic"));
                 view_phone.setText(rs.getString("phone"));
                 view_email.setText(rs.getString("email"));
                 view_address.setText(rs.getString("address"));
         }else{
                JOptionPane.showMessageDialog(null,"no data for this id");
            }
         }catch(Exception ex){
        System.out.println(ex);
    }  
    }//GEN-LAST:event_view_viewActionPerformed

    private void view_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_editActionPerformed
        // TODO add your handling code here:
         if(!"".equals(view_id.getText())&&!"".equals(view_name.getText())&&!"".equals(view_dob.getText())&&!"".equals(view_nic.getText())&&!"".equals(view_phone.getText())&&!"".equals(view_email.getText())&&!"".equals(view_address.getText())){
          try{
            String sql="update librarian set fullname=?,dob=?,nic=?,phone=?,email=?,address=? where id='"+view_id.getText()+"'";
            pst=conn.prepareStatement(sql);
            pst.setString(1, view_name.getText());
            pst.setString(2, view_dob.getText());
            pst.setString(3, view_nic.getText());
            pst.setString(4, view_phone.getText());
            pst.setString(5, view_email.getText());
            pst.setString(6, view_address.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "librarian updated");
            view_id.setText("");
            view_name.setText("");
            view_dob.setText("");
            view_nic.setText("");
            view_phone.setText("");
            view_email.setText("");
            view_address.setText("");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }   
        }else{
            JOptionPane.showMessageDialog(null,"please fill all the text fields"); 
         }
    }//GEN-LAST:event_view_editActionPerformed

    private void delete_librarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_librarianActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm=(DefaultTableModel)Delete_table.getModel();
        int getSelectedRow=Delete_table.getSelectedRow();
       /* if(getSelectedRow >=0){
            tm.removeRow(getSelectedRow);
            JOptionPane.showMessageDialog(null, "Row Deleted");*/
            String cell=Delete_table.getModel().getValueAt(getSelectedRow,0).toString();
            String sql="DELETE from librarian where id='"+cell+"'";
            try{
                ps=conn.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Librarian Deleted");
                display();
            } catch (SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        /*}else{
                JOptionPane.showMessageDialog(null,"Unable to Delete");
                }*/
    }//GEN-LAST:event_delete_librarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPanel;
    private javax.swing.JPanel DeletePanel;
    private javax.swing.JTable Delete_table;
    private javax.swing.JPanel ViewPanel1;
    private javax.swing.JPanel ViewPanel2;
    private javax.swing.JButton add;
    private javax.swing.JButton add_librarian;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete_librarian;
    private org.jdesktop.swingx.JXDatePicker dob;
    private javax.swing.JTextField email;
    private javax.swing.JPanel freePanel;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField phone;
    private javax.swing.JButton view;
    private javax.swing.JTextField view_address;
    private javax.swing.JTextField view_dob;
    private javax.swing.JButton view_edit;
    private javax.swing.JTextField view_email;
    private javax.swing.JTextField view_id;
    private javax.swing.JTextField view_name;
    private javax.swing.JTextField view_nic;
    private javax.swing.JTextField view_phone;
    private javax.swing.JButton view_view;
    // End of variables declaration//GEN-END:variables
}
