
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nimesha
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new javax.swing.JPanel();
        mainPanel2 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        student = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        minimize_btn = new javax.swing.JButton();
        guestLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        img2 = new javax.swing.JLabel();
        mainPanel3 = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        wlcm = new javax.swing.JLabel();
        toThe = new javax.swing.JLabel();
        LMS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        stdBtnPanel = new javax.swing.JPanel();
        check_btn = new javax.swing.JButton();
        view_label = new javax.swing.JLabel();
        check_label = new javax.swing.JLabel();
        view_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel1.setBackground(new java.awt.Color(153, 102, 0));
        mainPanel1.setLayout(new java.awt.GridLayout(1, 0));

        mainPanel2.setBackground(new java.awt.Color(153, 102, 0));

        buttonPanel.setBackground(new java.awt.Color(204, 204, 255));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student.setBackground(new java.awt.Color(204, 204, 255));
        student.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        student.setText("Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        buttonPanel.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, 60));

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/Actions-window-close-icon.png"))); // NOI18N
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        buttonPanel.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        minimize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/subtract-512.png"))); // NOI18N
        minimize_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimize_btnActionPerformed(evt);
            }
        });
        buttonPanel.add(minimize_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 50, 50));

        guestLogin.setBackground(new java.awt.Color(204, 204, 255));
        guestLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        guestLogin.setText("Guest Login");
        guestLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestLoginActionPerformed(evt);
            }
        });
        buttonPanel.add(guestLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 240, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        buttonPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, 270));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/customerimg.jpg"))); // NOI18N
        buttonPanel.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 680));

        mainPanel3.setLayout(new java.awt.CardLayout());

        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wlcm.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        wlcm.setText("WELCOME");
        welcomePanel.add(wlcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 280, 90));

        toThe.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        toThe.setText("TO THE");
        welcomePanel.add(toThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 210, 60));

        LMS.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        LMS.setText("LIBRARY MANAGEMENT SYSTEM!!!");
        welcomePanel.add(LMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 850, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/1060263_cream-backgrounds-photo-by-jenwilliams07_1024x1024_h.jpg"))); // NOI18N
        jLabel1.setText(" ");
        welcomePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 860, 270));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/customerimg.jpg"))); // NOI18N
        img1.setText("jLabel5");
        welcomePanel.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 680));

        mainPanel3.add(welcomePanel, "card2");

        stdBtnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/book_icon_book_showing_employee_business_book_Slide01 (2).jpg"))); // NOI18N
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });
        stdBtnPanel.add(check_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 156, -1));

        view_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view_label.setText("View Book Details");
        view_label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        stdBtnPanel.add(view_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, 37));

        check_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        check_label.setText("Check Availability");
        check_label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        stdBtnPanel.add(check_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, 40));

        view_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/114-1145783_transparent-book-vector-png-book-icon-vector-png[1].png"))); // NOI18N
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        stdBtnPanel.add(view_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 156, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/1060263_cream-backgrounds-photo-by-jenwilliams07_1024x1024_h.jpg"))); // NOI18N
        jLabel2.setText(" ");
        stdBtnPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 860, 270));

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/customerimg.jpg"))); // NOI18N
        img3.setText("jLabel8");
        stdBtnPanel.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 680));

        mainPanel3.add(stdBtnPanel, "card3");

        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel1.add(mainPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guestLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestLoginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_guestLoginActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
         mainPanel3.removeAll();
        mainPanel3.repaint();
        mainPanel3.revalidate();
        
        mainPanel3.add(stdBtnPanel);
        mainPanel3.repaint();
        mainPanel3.revalidate();
    }//GEN-LAST:event_studentActionPerformed

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        BookPanel ob=new BookPanel();
        ob.setVisible(true);
    }//GEN-LAST:event_check_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        StudentPage ob=new StudentPage();
        ob.setVisible(true);
    }//GEN-LAST:event_view_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void minimize_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize_btnActionPerformed
        // TODO add your handling code here:
         this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LMS;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton check_btn;
    private javax.swing.JLabel check_label;
    private javax.swing.JButton close_btn;
    private javax.swing.JButton guestLogin;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JPanel mainPanel2;
    private javax.swing.JPanel mainPanel3;
    private javax.swing.JButton minimize_btn;
    private javax.swing.JPanel stdBtnPanel;
    private javax.swing.JButton student;
    private javax.swing.JLabel toThe;
    private javax.swing.JButton view_btn;
    private javax.swing.JLabel view_label;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JLabel wlcm;
    // End of variables declaration//GEN-END:variables
}
