
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nimesha
 */

public class LibrarianPage extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianPage
     */
    Connection conn;




    public LibrarianPage() {
         
        
        initComponents();
        conn=javaConnect.connecrDb();
        Random();
        IsuedDate();
        DueDate();
        display();
        currentDate();
    }
public void Random(){
        Random rd=new Random();
        Book_id.setText(""+rd.nextInt(1000+1));
        
    }
public void IsuedDate(){
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
	LocalDate localDate2 = LocalDate.now();
        issue_date.setText(""+localDate2);
	//System.out.println(dtf.format(localDate)); //2016/11/16
}
public void DueDate(){
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
	LocalDate localDate1 = LocalDate.now().plusDays(14);
        due_date.setText(""+localDate1);
	//System.out.println(dtf.format(localDate)); //2016/11/16
}
public void currentDate(){
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
	LocalDate localDate0 = LocalDate.now();
        RBcurrent_date.setText(""+localDate0);
        RBreturn_date.setText(""+localDate0);
	//System.out.println(dtf.format(localDate)); //2016/11/16
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        view = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FreePanel = new javax.swing.JPanel();
        BGimg2 = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Book_id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        Book_author = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        publisher = new javax.swing.JTextField();
        edition = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        ViewBook = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        view_category = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        view_edition = new javax.swing.JTextField();
        view_author = new javax.swing.JTextField();
        view_publisher = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        view_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        view_issue = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueTable = new javax.swing.JTable();
        issuePanel = new javax.swing.JPanel();
        IBpanel1 = new javax.swing.JPanel();
        student_id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        book_id = new javax.swing.JTextField();
        issueBook_btn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        issue_date = new javax.swing.JTextField();
        due_date = new javax.swing.JTextField();
        IBpanel2 = new javax.swing.JPanel();
        book_name = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        IBedition = new javax.swing.JTextField();
        IBpublisher = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ReturnPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        RBbook_id = new javax.swing.JTextField();
        RBstudent_id = new javax.swing.JTextField();
        RBcurrent_date = new javax.swing.JTextField();
        RBreturn_date = new javax.swing.JTextField();
        RBbook_name = new javax.swing.JTextField();
        RBissue_date = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        RBdue_date = new javax.swing.JTextField();
        overdue = new javax.swing.JTextField();
        fine = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        return_btn = new java.awt.Button();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("issue");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("return");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 120, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("logout");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 120, 50));

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add_btn.setText("add");
        add_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 50));

        view.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View", "View Book", "View Issue" }));
        view.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/librarianmenu.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 204)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 960, 80));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        FreePanel.setBackground(new java.awt.Color(204, 204, 255));
        FreePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/Librarian-Beginning-of-School-Year-Checklist.png"))); // NOI18N
        BGimg2.setText("jLabel1");
        BGimg2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(227, 251, 150)));
        FreePanel.add(BGimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 960, 490));

        jPanel2.add(FreePanel, "card7");

        addPanel.setBackground(new java.awt.Color(204, 204, 255));
        addPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "Add New Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Book ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Author");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Category");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Edition");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Publisher");

        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/addnewbook.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Description");

        description.setColumns(20);
        description.setRows(5);
        jScrollPane2.setViewportView(description);

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(83, 83, 83)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Book_id)
                            .addComponent(name)
                            .addComponent(Book_author)
                            .addComponent(category)
                            .addComponent(publisher)
                            .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(107, 107, 107)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Book_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add)
                .addGap(33, 33, 33))
        );

        jPanel2.add(addPanel, "card2");

        ViewBook.setBackground(new java.awt.Color(204, 204, 255));
        ViewBook.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "View Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Enter the book ID:");

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/search.png"))); // NOI18N
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Name");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Category");

        view_edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_editionActionPerformed(evt);
            }
        });

        view_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_authorActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/edit icon.png"))); // NOI18N
        edit.setText("Edit Book");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Author");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Publisher");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Edition");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(view_author, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(view_publisher)
                            .addComponent(view_edition)
                            .addComponent(view_name)
                            .addComponent(view_category)))
                    .addComponent(edit))
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(view_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(view_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(view_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(view_edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(view_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit)
                .addContainerGap())
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/Viewbook.png"))); // NOI18N

        javax.swing.GroupLayout ViewBookLayout = new javax.swing.GroupLayout(ViewBook);
        ViewBook.setLayout(ViewBookLayout);
        ViewBookLayout.setHorizontalGroup(
            ViewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewBookLayout.createSequentialGroup()
                .addGroup(ViewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewBookLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel10)
                        .addGap(69, 69, 69)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(search))
                    .addGroup(ViewBookLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel16)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        ViewBookLayout.setVerticalGroup(
            ViewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewBookLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ViewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGroup(ViewBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewBookLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewBookLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(ViewBook, "card2");

        view_issue.setBackground(new java.awt.Color(204, 204, 255));
        view_issue.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "View Issued Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        issueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Book id", "Book Name", "Author", "Publisher", "Edition", "Student id", "Issued Date", "Due Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(issueTable);

        javax.swing.GroupLayout view_issueLayout = new javax.swing.GroupLayout(view_issue);
        view_issue.setLayout(view_issueLayout);
        view_issueLayout.setHorizontalGroup(
            view_issueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_issueLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        view_issueLayout.setVerticalGroup(
            view_issueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_issueLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jPanel2.add(view_issue, "card2");

        issuePanel.setBackground(new java.awt.Color(204, 204, 255));
        issuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "Issue Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Book ID");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Student ID");

        book_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book_idMouseExited(evt);
            }
        });

        issueBook_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issueBook_btn.setText("Issue Book");
        issueBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBook_btnActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Issue Date");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Due Date");

        javax.swing.GroupLayout IBpanel1Layout = new javax.swing.GroupLayout(IBpanel1);
        IBpanel1.setLayout(IBpanel1Layout);
        IBpanel1Layout.setHorizontalGroup(
            IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IBpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(issueBook_btn)
                    .addGroup(IBpanel1Layout.createSequentialGroup()
                        .addGroup(IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(83, 83, 83)
                        .addGroup(IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(student_id, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(book_id)
                            .addComponent(issue_date)
                            .addComponent(due_date))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        IBpanel1Layout.setVerticalGroup(
            IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IBpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(student_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(issue_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(IBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(due_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(issueBook_btn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        IBpanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Book Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Author");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Edition");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Book Name");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Publisher");

        javax.swing.GroupLayout IBpanel2Layout = new javax.swing.GroupLayout(IBpanel2);
        IBpanel2.setLayout(IBpanel2Layout);
        IBpanel2Layout.setHorizontalGroup(
            IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IBpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(book_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(author, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IBpublisher, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IBedition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        IBpanel2Layout.setVerticalGroup(
            IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IBpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(24, 24, 24)
                .addGroup(IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(25, 25, 25)
                .addGroup(IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IBpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(25, 25, 25)
                .addGroup(IBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IBedition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout issuePanelLayout = new javax.swing.GroupLayout(issuePanel);
        issuePanel.setLayout(issuePanelLayout);
        issuePanelLayout.setHorizontalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuePanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(IBpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(IBpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        issuePanelLayout.setVerticalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuePanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IBpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IBpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel2.add(issuePanel, "card2");

        ReturnPanel.setBackground(new java.awt.Color(204, 204, 255));
        ReturnPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "Return Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Enter Book ID");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Enter Student ID");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Current Date");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Actual Return Date");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Book Name");

        RBbook_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RBbook_idMouseExited(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Date of Issue");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Due Date");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Overdated Days");

        overdue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                overdueMouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("Fine Amount");

        return_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        return_btn.setLabel("Return Book");
        return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReturnPanelLayout = new javax.swing.GroupLayout(ReturnPanel);
        ReturnPanel.setLayout(ReturnPanelLayout);
        ReturnPanelLayout.setHorizontalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(return_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReturnPanelLayout.createSequentialGroup()
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(19, 19, 19)
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RBcurrent_date)
                            .addComponent(RBbook_id)
                            .addComponent(RBstudent_id)
                            .addComponent(RBreturn_date, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(39, 39, 39)
                        .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ReturnPanelLayout.createSequentialGroup()
                                .addComponent(overdue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33)
                                .addGap(29, 29, 29)
                                .addComponent(fine, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RBbook_name)
                            .addComponent(RBissue_date, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RBdue_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        ReturnPanelLayout.setVerticalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(RBbook_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(RBbook_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(RBstudent_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBissue_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(33, 33, 33)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(RBcurrent_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(RBdue_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(RBreturn_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overdue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(fine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(88, 88, 88)
                .addComponent(return_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel2.add(ReturnPanel, "card2");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/back.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryMangementSystem/images/Actions-window-close-icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void view_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_authorActionPerformed

    private void view_editionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_editionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_editionActionPerformed
private void display(){
    ResultSet rs0;

    try{/*String cart="select * from cart\n" +
"        JOIN cardpay\n" +
"             on cart.customer_id = cardpay.customer_id"  ;*/
        String issue="select * from issued_books\n"+"JOIN book\n"+"on issued_books.book_id = book.id";
        PreparedStatement pst=conn.prepareStatement(issue);
        rs0=pst.executeQuery();
        DefaultTableModel tm=(DefaultTableModel)issueTable.getModel();
         tm.setRowCount(0);
         while(rs0.next()){
             Object o[]={rs0.getString("id"),rs0.getString("name"),rs0.getString("author"),rs0.getString("publisher"),rs0.getInt("edition"),rs0.getString("student_id"),rs0.getString("issued_date"),rs0.getString("due_date")};
              tm.addRow(o);
             }
        }catch(Exception ex){
        System.out.println(ex);
    }
     
    }
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(addPanel);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_add_btnActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        if((String) view.getSelectedItem()=="View Book"){
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(ViewBook);
        jPanel2.repaint();
        jPanel2.revalidate();
        }
        else if((String) view.getSelectedItem()=="View Issue"){
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(view_issue);
        jPanel2.repaint();
        jPanel2.revalidate();
        }
    }//GEN-LAST:event_viewActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(issuePanel);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(ReturnPanel);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst1;
        PreparedStatement ps1;
        if(!"".equals(Book_id.getText())&&!"".equals(name.getText())&&!"".equals(Book_author.getText())&&!"".equals(category.getText())&&!"0".equals(edition.getValue().toString())&&!"".equals(publisher.getText())&&!"".equals(description.getText())){
        String sql1="insert into book(id,name,author,category,edition,publisher,description) values(?,?,?,?,?,?,?)";
        //String sql2="insert into available_books(id,name,author,edition,publisher) values(?,?,?,?,?)";
        try{
            pst1=conn.prepareStatement(sql1);
            //ps1=conn.prepareStatement(sql2);
            pst1.setString(1, Book_id.getText());
            pst1.setString(2, name.getText());
            pst1.setString(3, Book_author.getText());
            pst1.setString(4, category.getText());
            pst1.setString(5, edition.getValue().toString());
            pst1.setString(6, publisher.getText());
            pst1.setString(7, description.getText());
            pst1.execute();
//            ps1.setString(1, Book_id.getText());
//            ps1.setString(2, name.getText());
//            ps1.setString(3, Book_author.getText());
//            ps1.setString(5, edition.getValue().toString());
//            ps1.setString(6, publisher.getText());
//            ps1.execute();
            JOptionPane.showMessageDialog(null, "new book added");
            Book_id.setText("");
            name.setText("");
            Book_author.setText("");
            category.setText("");
            //edition.setValue(0);
            publisher.setText("");
            description.setText("");
                            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }    
        }else{
            JOptionPane.showMessageDialog(null,"please fill all the text fields"); 
        }
        
    }//GEN-LAST:event_addActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        ResultSet rs1;

        PreparedStatement pst2;
        try{
        String book="Select * from book where id=?"  ;
       pst2=conn.prepareStatement(book);
       pst2.setString(1,ID.getText());
        rs1=pst2.executeQuery();
        if(rs1.next()){
           
                 view_name.setText(rs1.getString("name"));
                 view_author.setText(rs1.getString("author"));
                 view_publisher.setText(rs1.getString("publisher"));
                 view_edition.setText(rs1.getString("edition"));
                 view_category.setText(rs1.getString("category"));
                
         }else{
                JOptionPane.showMessageDialog(null,"no data for this id");
            }
         }catch(Exception ex){
        System.out.println(ex);
    }  
    }//GEN-LAST:event_searchActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst3;
        PreparedStatement ps2;
        if(!"".equals(ID.getText())&&!"".equals(view_name.getText())&&!"".equals(view_author.getText())&&!"".equals(view_publisher.getText())&&!"".equals(view_edition.getText())&&!"".equals(view_category.getText())){
          try{
            String sql5="update book set name=?,author=?,publisher=?,edition=?,category=? where id='"+ID.getText()+"'";
            //String sql6="update available_books set name=?,author=?,publisher=?,edition=? where id='"+ID.getText()+"'";
            pst3=conn.prepareStatement(sql5);
            //ps2=conn.prepareStatement(sql6);
            pst3.setString(1, view_name.getText());
            pst3.setString(2, view_author.getText());
            pst3.setString(3, view_publisher.getText());
            pst3.setString(4, view_edition.getText());
            pst3.setString(5, view_category.getText());
            pst3.execute();
//            ps2.setString(1, view_name.getText());
//            ps2.setString(2, view_author.getText());
//            ps2.setString(3, view_publisher.getText());
//            ps2.setString(4, view_edition.getText());
//            ps2.execute();
            JOptionPane.showMessageDialog(null, "book updated");
            ID.setText("");
            view_name.setText("");
            view_author.setText("");
            view_publisher.setText("");
            view_edition.setText("");
            view_category.setText("");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }   
        }else{
            JOptionPane.showMessageDialog(null,"please fill all the text fields"); 
         }
    }//GEN-LAST:event_editActionPerformed

    private void issueBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBook_btnActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps0;
        PreparedStatement ps3;
        PreparedStatement pst4;
        ResultSet rs2;

        String sql1="select * from issued_books where book_id=?";
        try{
            ps3=conn.prepareStatement(sql1);
            ps3.setString(1,book_id.getText());
            rs2=ps3.executeQuery();
            if(rs2.next()){
            JOptionPane.showMessageDialog(null,"Book not available");
            
            book_id.setText("");
            author.setText("");
            book_name.setText("");
            IBedition.setText("");
            IBpublisher.setText("");
            }else{
              if(!"".equals(book_id.getText())&&!"".equals(student_id.getText())&&!"".equals(issue_date.getText())&&!"".equals(due_date.getText())){
        
//        String sql3="Delete from available_books where id='"+book_id.getText()+"'";
//        try{
//            ps0=conn.prepareStatement(sql3);
//            ps0.execute();
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null,e);
//        }
            String sql0="insert into issued_books(Student_id,book_id,Issued_date,Due_date) values(?,?,?,?)";
            try{
                
            pst4=conn.prepareStatement(sql0);
            pst4.setString(1, student_id .getText());
            pst4.setString(2, book_id.getText());
            pst4.setString(3, issue_date.getText());
            pst4.setString(4, due_date.getText());
            pst4.execute();
            JOptionPane.showMessageDialog(null, "Book issued");
            student_id .setText("");
            book_id.setText("");
            author.setText("");
            book_name.setText("");
            IBedition.setText("");
            IBpublisher.setText("");
            display();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }    
        }else{
            JOptionPane.showMessageDialog(null,"please fill all the text fields"); 
        }
          
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LibrarianPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_issueBook_btnActionPerformed

    private void book_idMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_idMouseExited
        // TODO add your handling code here:
        PreparedStatement pst5;
        ResultSet rs3;

      try{
        String book="Select * from book where id=?"  ;
       pst5=conn.prepareStatement(book);
       pst5.setString(1,book_id.getText());
        rs3=pst5.executeQuery();
        if(rs3.next()){
           
                 book_name.setText(rs3.getString("name"));
                 author.setText(rs3.getString("author"));
                 IBpublisher.setText(rs3.getString("publisher"));
                 IBedition.setText(rs3.getString("edition"));
                 issueBook_btn.setEnabled(true);
                
         }else{
                JOptionPane.showMessageDialog(null,"no data for this id");
                issueBook_btn.setEnabled(false);
                book_id.setText("");
            }
         }catch(Exception ex){
        System.out.println(ex);
    }    
    }//GEN-LAST:event_book_idMouseExited
    private void daysBetween(Date one, Date two) { 
    long difference = (one.getTime()-two.getTime())/86400000; 
    long days = Math.abs(difference);
    
    }
    public void fineAmount(){
    /*LocalDate localDate1 = LocalDate.now().plusDays(14);
    LocalDate localDate0 = LocalDate.now();
    //int days = Days.daysBetween(date1, date2).getDays();
    //int daysBetween = day1.get(Calendar.DAY_OF_YEAR) - day2.get(Calendar.DAY_OF_YEAR); 
    /*if(RBreturn_date.getText()==RBdue_date.getText()){
            overdue.setText("0");
            fine.setText("0.00");
        }else(){
            
        }*/
      /*if(localDate0.compareTo(localDate1) > 0) {
         //System.out.println("Date 1 occurs after Date 2");
         Date one=myFormat.parse(dateAfterString);
         Date two=localDate1.getTime();
      } else if(localDate0.compareTo(localDate1) < 0) {
         //System.out.println("Date 1 occurs before Date 2");
         overdue.setText("0");
         fine.setText("0.00");
      } else if(localDate0.compareTo(localDate1) == 0) {
         //System.out.println("Both dates are equal");
         overdue.setText("0");
         fine.setText("0.00");
      }*/
      String fine2=overdue.getText();
      int fine1 =Integer.parseInt(fine2)*5;
      fine.setText(String.valueOf(fine1));
        
}
    private void RBbook_idMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBbook_idMouseExited
        // TODO add your handling code here:
        PreparedStatement pst6;
        PreparedStatement ps4;
        ResultSet rs4;
        ResultSet sr0;
        try{
        String rtrn="Select * from issued_books where book_id=?"  ;
        String bkName="Select name from book where id=?"  ;
        pst6=conn.prepareStatement(rtrn);
        ps4=conn.prepareStatement(bkName);
        pst6.setString(1,RBbook_id.getText());
        ps4.setString(1,RBbook_id.getText());
        rs4=pst6.executeQuery();
        if(rs4.next()){
           
                 RBstudent_id.setText(rs4.getString("student_id"));
                 RBissue_date.setText(rs4.getString("issued_date"));
                 RBdue_date.setText(rs4.getString("due_date"));
                 return_btn.setEnabled(true);
                
         }else{
                JOptionPane.showMessageDialog(null,"no data for this id");
                return_btn.setEnabled(false);
                RBbook_id.setText("");
                RBstudent_id.setText("");
                RBissue_date.setText("");
                RBdue_date.setText("");
                RBbook_name.setText("");
                overdue.setText("");
                fine.setText("");
            }
        sr0=ps4.executeQuery();
        if(sr0.next()){
           
                 RBbook_name.setText(sr0.getString("name"));
        }
        
         }catch(Exception ex){
        System.out.println(ex);
    }     
    }//GEN-LAST:event_RBbook_idMouseExited

    private void overdueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overdueMouseExited
        // TODO add your handling code here:
        fineAmount();
    }//GEN-LAST:event_overdueMouseExited

    private void return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btnActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps5;
        PreparedStatement pst7;
        PreparedStatement ps6;
        if(!"".equals(RBbook_id.getText())&&!"".equals(fine.getText())){
            String sql="Delete from issued_books where book_id='"+RBbook_id.getText()+"'";
            /*SELECT column1, column2, column3, ...
INTO newtable [IN externaldb]
FROM oldtable
WHERE condition;*/
            //String bkdetails= "INSERT INTO available_books(id,name,author,edition,publisher) SELECT id,name,author,edition,publisher FROM book WHERE id=?";
            /*(author,edition,publisher)*/
            //String bkdetails="select id,name,author,edition,publisher insert into available_books from book where id=?";
            
            try{
            pst7=conn.prepareStatement(sql);
            pst7.execute();
            
           /* String sql4="insert into available_books(id,name) values(?,?)";
            ps5=conn.prepareStatement(sql4);
            System.out.println("3");
            ps.setString(1, RBbook_id.getText());
            System.out.println("31");
            ps5.setString(2, RBbook_name.getText());
            ps5.execute();*/
//            ps6=conn.prepareStatement(bkdetails);
//            ps6.execute();
            JOptionPane.showMessageDialog(null, "Book Returned");
            RBbook_id.setText("");
            RBstudent_id.setText("");
            RBissue_date.setText("");
            RBdue_date.setText("");
            RBbook_name.setText("");
            overdue.setText("");
            fine.setText("");
            
            } catch (SQLException ex) {
                Logger.getLogger(LibrarianPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
           JOptionPane.showMessageDialog(null, "Please fill all the fields"); 
        }
    }//GEN-LAST:event_return_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGimg2;
    private javax.swing.JTextField Book_author;
    private javax.swing.JTextField Book_id;
    private javax.swing.JPanel FreePanel;
    private javax.swing.JTextField IBedition;
    private javax.swing.JPanel IBpanel1;
    private javax.swing.JPanel IBpanel2;
    private javax.swing.JTextField IBpublisher;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField RBbook_id;
    private javax.swing.JTextField RBbook_name;
    private javax.swing.JTextField RBcurrent_date;
    private javax.swing.JTextField RBdue_date;
    private javax.swing.JTextField RBissue_date;
    private javax.swing.JTextField RBreturn_date;
    private javax.swing.JTextField RBstudent_id;
    private javax.swing.JPanel ReturnPanel;
    private javax.swing.JPanel ViewBook;
    private javax.swing.JButton add;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField author;
    private javax.swing.JTextField book_id;
    private javax.swing.JTextField book_name;
    private javax.swing.JTextField category;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField due_date;
    private javax.swing.JButton edit;
    private javax.swing.JSpinner edition;
    private javax.swing.JTextField fine;
    private javax.swing.JButton issueBook_btn;
    private javax.swing.JPanel issuePanel;
    private javax.swing.JTable issueTable;
    private javax.swing.JTextField issue_date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField name;
    private javax.swing.JTextField overdue;
    private javax.swing.JTextField publisher;
    private java.awt.Button return_btn;
    private javax.swing.JButton search;
    private javax.swing.JTextField student_id;
    private javax.swing.JComboBox<String> view;
    private javax.swing.JTextField view_author;
    private javax.swing.JTextField view_category;
    private javax.swing.JTextField view_edition;
    private javax.swing.JPanel view_issue;
    private javax.swing.JTextField view_name;
    private javax.swing.JTextField view_publisher;
    // End of variables declaration//GEN-END:variables
}
